name: DESPOT

channels:
  - conda-forge
  - defaults

dependencies:
  - python
  - requests
  - urllib3
  - numpy
  - numba
  - pandas
  - pyarrow
  - scikit-learn
  - biopython
  - joblib
  - matplotlib
  - seaborn
  - scipy
  - tqdm
  - einops
  - networkx
  - pip
  - pip:
      - scikit-posthocs
      - biopandas
